# Databricks notebook source
from pyspark.sql import functions as F

# COMMAND ----------

 %run ./mhsds_functions

# COMMAND ----------

breakdowns_metdata = { 'England'  :{'name':'England',
                                    'column':'"England"',
                                    'namecol':'"England"',
                                    'level_list': [("England", )],
#                                     'level_fields' : [
#                                                       F.lit("England").alias("breakdown"),  
#                                                       F.lit("England").alias("primary_level"),
#                                                       F.lit("England").alias("primary_level_desc"),
#                                                       F.lit("NONE").alias("secondary_level"), 
#                                                       F.lit("NONE").alias("secondary_level_desc")
#                                                       ],
                                    'lookup_col' : ["England"]},
                       'Age'      :{'name':'Age Group',
                                    'column':'Der_AgeGroup',
                                    'namecol':'Der_AgeGroup',
                                    'level_list': [            
                                                    ("0 to 17", ),
                                                    ("18 to 24", ),           
                                                    ("25 to 29", ),             
                                                    ("30 to 34", ),           
                                                    ("35 to 39", ),             
                                                    ("40 to 44", ),           
                                                    ("45 to 49", ),             
                                                    ("50 to 54", ),           
                                                    ("55 to 59", ),             
                                                    ("60 to 64", ),           
                                                    ("65 plus", ),             
                                                    ("UNKNOWN", ),
                                        ],
                                    'lookup_col' : ["Der_AgeGroup"]
                                   },
                       'Ethnicity':{'name':'Ethnicity',
                                    'column':'NHSDEthnicity',
                                    'namecol':'NHSDEthnicityName',
                                    'level_list': [            
                                                    ("A", "British"),             
                                                    ("B", "Irish"),
                                                    ("C", "Any Other White Background"),
                                                    ("D", "White and Black Caribbean"),
                                                    ("E", "White and Black African"),
                                                    ("F", "White and Asian"),
                                                    ("G", "Any Other mixed background"),
                                                    ("H", "Indian"),
                                                    ("J", "Pakistani"), 
                                                    ("K", "Bangladeshi"),
                                                    ("L", "Any Other Asian background"),
                                                    ("M", "Caribbean"),
                                                    ("N", "African"),
                                                    ("P", "Any Other Black background"),
                                                    ("R", "Chinese"),
                                                    ("S", "Any Other Ethnic Group"),
                                                    ("Z", "Not Stated"),
                                                    ("99", "Not Known"),
                                                    ("UNKNOWN", "UNKNOWN"),
                                        ],
                                    'lookup_col' : ["NHSDEthnicity","NHSDEthnicityName"]},
                       'GENDER'   :{'name':'Gender',
                                    'column':'Der_Gender',
                                    'namecol':'Der_GenderName',
                                    'level_list': [            
                                                    ("1", "Male"),             
                                                    ("2", "Female"),
                                                    ("3", "Non-binary"),
                                                    ("4", "Other (not listed)"),
                                                    ("9", "Indeterminate"),            
                                                    ("UNKNOWN", "UNKNOWN"),
                                        ],
                                    'lookup_col' : ["Der_Gender","Der_GenderName"]},
                       'IMD'      :{'name':'IMD',
                                    'column':'IMD_Decile',
                                    'namecol':'IMD_Decile',
                                    'level_list': [            
                                                    ("01 Most deprived", ),             
                                                    ("02 More deprived", ),
                                                    ("03 More deprived", ),
                                                    ("04 More deprived", ),
                                                    ("05 More deprived", ),
                                                    ("06 Less deprived", ),
                                                    ("07 Less deprived", ),
                                                    ("08 Less deprived", ),
                                                    ("09 Less deprived", ), 
                                                    ("10 Least deprived", ),
                                                    ("UNKNOWN", ),
                                        ],
                                    'lookup_col' : ["IMD_Decile"]},
                       'Reason'   :{'name':'Primary reason for referral',
                                    'column':'PrimReasonReferralMH',
                                    'namecol':'PrimReasonReferralMHName',
                                    'level_list': [            
                                                    ('01','(Suspected) First Episode Psychosis'),
                                                    ('02','Ongoing or Recurrent Psychosis'),
                                                    ('03','Bi polar disorder'),
                                                    ('04','Depression'),
                                                    ('05','Anxiety'),
                                                    ('06','Obsessive compulsive disorder'),
                                                    ('07','Phobias'),
                                                    ('08','Organic brain disorder'),
                                                    ('09','Drug and alcohol difficulties '),
                                                    ('10','Unexplained physical symptoms'),
                                                    ('11','Post-traumatic stress disorder'),
                                                    ('12','Eating disorders'),
                                                    ('13','Perinatal mental health issues'),
                                                    ('14','Personality disorders'),
                                                    ('15','Self harm behaviours'),
                                                    ('16','Conduct disorders'),
                                                    ('18','In crisis'),
                                                    ('19','Relationship difficulties'),
                                                    ('20','Gender Discomfort issues'),
                                                    ('21','Attachment difficulties '),
                                                    ('22','Self - care issues'),
                                                    ('23','Adjustment to health issues'),
                                                    ('24','Neurodevelopmental Conditions, excluding Autism '),
                                                    ('25','Suspected Autism '),
                                                    ('26','Diagnosed Autism'),
                                                    ('27','Preconception perinatal mental health concern'),
                                                    ('28','Gambling disorder'),
                                                    ('29','Community Perinatal Mental Health Partner Assessment'),
                                                    ('30','Behaviours that challenge due to a Learning Disability'),
                                                    ('UNKNOWN','UNKNOWN'),
                                        ],
                                    'lookup_col' : ["PrimReasonReferralMH","PrimReasonReferralMHName"]},
                       'BedType'  :{'name':'Bed Type',
                                    'column':'HospitalBedTypeMH',
                                    'namecol':'HospitalBedTypeMHName',
                                    'level_list': [            
                                                    ('10','Acute adult mental health care'),
                                                    ('11','Acute older adult mental health care (organic and functional)'),
                                                    ('12','Adult Psychiatric Intensive Care Unit (acute mental health care)'),
                                                    ('13','Adult Eating Disorders'),
                                                    ('14','Mother and baby'),
                                                    ('15','Adult Learning Disabilities'),
                                                    ('17','Adult High dependency rehabilitation'),
                                                    ('19','Adult Low secure'),
                                                    ('20','Adult Medium secure'),
                                                    ('21','Adult High secure'),
                                                    ('22','Adult Neuro-psychiatry / Acquired Brain Injury'),
                                                    ('23','General child and young PERSON admitted PATIENT - Child (including High Dependency)'),
                                                    ('24','General child and young PERSON admitted PATIENT - Young PERSON (including High Dependency)'),
                                                    ('25','Eating Disorders admitted patient - Young person (13 years and over)'),
                                                    ('26','Eating Disorders admitted patient - Child (12 years and under)'),
                                                    ('27','Child and Young Person Low Secure Mental Illness'),
                                                    ('28','Child and Young Person Medium Secure Mental Illness'),
                                                    ('29','Child Mental Health admitted patient services for the Deaf'),
                                                    ('30','Child and Young Person Learning Disabilities / Autism admitted patient'),
                                                    ('31','Child and Young Person Low Secure Learning Disabilities'),
                                                    ('32','Child and Young Person Medium Secure Learning Disabilities'),
                                                    ('33','Severe Obsessive Compulsive Disorder and Body Dysmorphic Disorder - Young person'),
                                                    ('34','Child and Young Person Psychiatric Intensive Care Unit'),
                                                    ('35','Adult admitted patient continuing care'),
                                                    ('36','Adult community rehabilitation unit'),
                                                    ('37','Adult highly specialist high dependency rehabilitation unit'),
                                                    ('38','Adult longer term high dependency rehabilitation unit'),
                                                    ('39','Adult mental health admitted patient services for the Deaf'),
                                                    ('40','Adult personality disorder'),
                                                    ('UNKNOWN','UNKNOWN'),
                                        ],
                                    'lookup_col' : ["HospitalBedTypeMH","HospitalBedTypeMHName"]},
                       'RECPROV'  :{'name':'Receiving Provider',
                                    'column':'OrgIDReceiving',
                                    'namecol':'ReceivingProvName',
                                    'level_list': [ ],
                                    'lookup_col' : []}
                       }

# COMMAND ----------

geog_breakdown_metadata = {'England' : {'name':'England',
                                        'codecol':'"England"',
                                        'namecol':'"England"',
                                        'incl_breakdowns_month':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType'],
                                        'incl_breakdowns_quarter':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType'],
                                        'geogtable':'',
                                        'geogcol':'',
                                        'geognamecol':''
                                       },
                           'SubICB'  : {'name':'Sub ICB Location - GP Practice or Residence',
                                        'codecol':'CCG_CODE',
                                        'namecol':'CCG_NAME',
                                        'incl_breakdowns_month':['England'],
                                        'incl_breakdowns_quarter':['England'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'geogtable':'OAPs_STP_Region_mapping',
                                        'geogcol':'CCG_CODE',
                                        'geognamecol':'CCG_NAME'
                                       },
                           'ICB'     : {'name':'ICB',
                                        'codecol':'STP_CODE',
                                        'namecol':'STP_NAME',
                                        'incl_breakdowns_month':['England'],
                                        'incl_breakdowns_quarter':['England'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'geogtable':'OAPs_STP_Region_mapping',
                                        'geogcol':'STP_CODE',
                                        'geognamecol':'STP_NAME'
                                       },
                           'REGION'  : {'name':'Region',
                                        'codecol':'REGION_CODE',
                                        'namecol':'REGION_NAME',
                                        'incl_breakdowns_month':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'incl_breakdowns_quarter':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'geogtable':'OAPs_STP_Region_mapping',
                                        'geogcol':'REGION_CODE',
                                        'geognamecol':'REGION_NAME'
                                       },
                           'SENDPROV': {'name':'Sending Provider',
                                        'codecol':'OrgIDSubmitting',
                                        'namecol':'SendingProvName',
                                        'incl_breakdowns_month':['England','RECPROV'],
                                        'incl_breakdowns_quarter':['England','RECPROV'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType','RECPROV'],
                                        'geogtable':'',
                                        'geogcol':'',
                                        'geognamecol':''
                                       },
                           'RECPROV' : {'name':'Receiving Provider',
                                        'codecol':'OrgIDReceiving',
                                        'namecol':'ReceivingProvName',
                                        'incl_breakdowns_month':['England'],
                                        'incl_breakdowns_quarter':['England'],
                                        'incl_breakdowns_year':['England','Age','Ethnicity','GENDER','IMD','Reason','BedType'],
                                        'geogtable':'',
                                        'geogcol':'',
                                        'geognamecol':''
                                       }
                          }

# COMMAND ----------

measure_metadata = {'OAP01' : {'name'     : 'Number of Inappropriate OAPs (not bed-nights) started in the period',
                               'type'     : 'count',
                               'aggcol'   : 'DISTINCT UniqServReqID',
                               'reasonoat': '10',
                               'activeend': ''},
                    'OAP02' : {'name'     : 'Number of Inappropriate OAPs bed days in the period',
                               'type'     : 'sum',
                               'aggcol'   : 'Bed_Days',
                               'reasonoat': '10',
                               'activeend': ''},
                    'OAP03' : {'name'     : 'Number of Inappropriate OAPs (not bed-nights) active at the end of the period',
                               'type'     : 'count',
                               'aggcol'   : 'DISTINCT UniqServReqID',
                               'reasonoat': '10',
                               'activeend': 'yes'},
                    'OAP04' : {'name'     : 'Number of Inappropriate OAPs (not bed-nights) ended in the period',
                               'type'     : 'count',
                               'aggcol'   : 'DISTINCT UniqServReqID',
                               'reasonoat': '10',
                               'activeend': ''}
                  }
measure_metadata

# COMMAND ----------

