# Databricks notebook source
# dbutils.widgets.text("db_output", "")
# db_output  = dbutils.widgets.get("db_output")

# dbutils.widgets.text("db_source", "$mhsds")
# db_source = dbutils.widgets.get("db_source")

# dbutils.widgets.text("month_id", "1446")
# month_id = dbutils.widgets.get("month_id")

# dbutils.widgets.text("rp_startdate", "2020-09-01")
# rp_startdate = dbutils.widgets.get("rp_startdate")

# dbutils.widgets.text("rp_enddate", "2020-09-30")
# rp_enddate = dbutils.widgets.get("rp_enddate")

# COMMAND ----------

db_output  = dbutils.widgets.get("db_output")
db_source = dbutils.widgets.get("db_source")
month_id = dbutils.widgets.get("month_id")
rp_enddate = dbutils.widgets.get("rp_enddate")
rp_startdate = dbutils.widgets.get("rp_startdate")

# COMMAND ----------

 %sql
 CREATE OR REPLACE TEMP VIEW SUBS_TEST AS 
 select
 ReportingPeriodEndDate, ReportingPeriodStartDate ,
 uniqmonthid, 
 ORGIDPROVIDER,
 MAX(UniqSubmissionID) AS UNIQSUBMISSIONID
 from
 $db_source.mhs000header
 -- where
 -- FILETYPE <= 2
 -- -- AND UNIQMONTHID <= '$month_id'
 GROUP BY 
 ReportingPeriodEndDate, ReportingPeriodStartDate , UNIQMONTHID, ORGIDPROVIDER

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMP VIEW RESTRAINTS_PERFORMANCE AS
 select
 a.person_id, a.orgidprov, a.uniqmonthid, a.uniqsubmissionid, a.restrictiveinttype, a.uniqwardstayid, a.mhs505uniqid, a.startdaterestrictiveint, a.enddaterestrictiveint, a.starttimerestrictiveint, a.endtimerestrictiveint,
 a.recordnumber
 from $db_source.mhs505restrictiveintervention a
 inner join SUBS_TEST b on a.uniqsubmissionid = b.uniqsubmissionid and a.uniqmonthid = b.uniqmonthid and a.orgidprov = b.orgidprovider
 -- where a.uniqmonthid = '$month_id'

# COMMAND ----------

# DBTITLE 1,Load Pre-determined List of Providers who should submit Restraints data according to NHS England
import pandas as pd
import io

data = """OrgCode,OrgName
RBS,ALDER HEY CHILDREN'S NHS FOUNDATION TRUST
RVN,AVON AND WILTSHIRE MENTAL HEALTH PARTNERSHIP NHS TRUST
RRP,"BARNET, ENFIELD AND HARINGEY MENTAL HEALTH NHS TRUST"
RWX,BERKSHIRE HEALTHCARE NHS FOUNDATION TRUST
RXT,BIRMINGHAM AND SOLIHULL MENTAL HEALTH NHS FOUNDATION TRUST
RQ3,BIRMINGHAM WOMEN'S AND CHILDREN'S NHS FOUNDATION TRUST
TAJ,BLACK COUNTRY HEALTHCARE NHS FOUNDATION TRUST
TAD,BRADFORD DISTRICT CARE NHS FOUNDATION TRUST
AHY,BRAMLEY HEALTH
RT1,CAMBRIDGESHIRE AND PETERBOROUGH NHS FOUNDATION TRUST
AMX8,CARETECH COMMUNITY SERVICES LTD
RV3,CENTRAL AND NORTH WEST LONDON NHS FOUNDATION TRUST
R0A,MANCHESTER UNIVERSITY NHS FOUNDATION TRUST
RXA,CHESHIRE AND WIRRAL PARTNERSHIP NHS FOUNDATION TRUST
RJ8,CORNWALL PARTNERSHIP NHS FOUNDATION TRUST
RYG,COVENTRY AND WARWICKSHIRE PARTNERSHIP NHS TRUST
RX4,"CUMBRIA, NORTHUMBERLAND, TYNE AND WEAR NHS FOUNDATION TRUST"
NMJ,CYGNET HEALTH CARE LIMITED
RXM,DERBYSHIRE HEALTHCARE NHS FOUNDATION TRUST
RWV,DEVON PARTNERSHIP NHS TRUST
RDY,DORSET HEALTHCARE UNIVERSITY NHS FOUNDATION TRUST
RWK,EAST LONDON NHS FOUNDATION TRUST
DN7,ELLERN MEDE
DE8,ELYSIUM HEALTHCARE
R1L,ESSEX PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST
RTQ,GLOUCESTERSHIRE HEALTH AND CARE NHS FOUNDATION TRUST
RP4,GREAT ORMOND STREET HOSPITAL FOR CHILDREN NHS FOUNDATION TRUST
RXV,GREATER MANCHESTER MENTAL HEALTH NHS FOUNDATION TRUST
AHX,LUDLOW STREET HEALTHCARE (HQ)
RWR,HERTFORDSHIRE PARTNERSHIP UNIVERSITY NHS FOUNDATION TRUST
RV9,HUMBER TEACHING NHS FOUNDATION TRUST
AHL,INMIND HEALTHCARE - HEAD OFFICE
RXY,KENT AND MEDWAY NHS AND SOCIAL CARE PARTNERSHIP TRUST
RW5,LANCASHIRE AND SOUTH CUMBRIA NHS FOUNDATION TRUST
RGD,LEEDS AND YORK PARTNERSHIP NHS FOUNDATION TRUST
RY6,LEEDS COMMUNITY HEALTHCARE NHS TRUST
RT5,LEICESTERSHIRE PARTNERSHIP NHS TRUST
RP7,LINCOLNSHIRE PARTNERSHIP NHS FOUNDATION TRUST
NR5,LIVEWELL SOUTHWEST
RW4,MERSEY CARE NHS FOUNDATION TRUST
RRE,MIDLANDS PARTNERSHIP NHS FOUNDATION TRUST
NQL,NAVIGO HEALTH AND SOCIAL CARE CIC
ATM,NEWBRIDGE CARE SYSTEMS LTD
8A867,NEWMARKET HOUSE HEALTHCARE LTD
RMY,NORFOLK AND SUFFOLK NHS FOUNDATION TRUST
RAT,NORTH EAST LONDON NHS FOUNDATION TRUST
RLY,NORTH STAFFORDSHIRE COMBINED HEALTHCARE NHS TRUST
RTV,NORTH WEST BOROUGHS HEALTHCARE NHS FOUNDATION TRUST
RP1,NORTHAMPTONSHIRE HEALTHCARE NHS FOUNDATION TRUST
RHA,NOTTINGHAMSHIRE HEALTHCARE NHS FOUNDATION TRUST
RNU,OXFORD HEALTH NHS FOUNDATION TRUST
RPG,OXLEAS NHS FOUNDATION TRUST
NMV,PARTNERSHIPS IN CARE LTD
RT2,PENNINE CARE NHS FOUNDATION TRUST
NTN,PRIORY GROUP LIMITED
8WH14,REGIS HEALTHCARE LIMITED
NRC,RIVERDALE GRANGE LIMITED
NRN,RIVERSIDE HEALTHCARE (CHESWOLD PARK HOSPITAL)
RXE,ROTHERHAM DONCASTER AND SOUTH HUMBER NHS FOUNDATION TRUST
RCU,SHEFFIELD CHILDREN'S NHS FOUNDATION TRUST
TAH,SHEFFIELD HEALTH & SOCIAL CARE NHS FOUNDATION TRUST
RH5,SOMERSET NHS FOUNDATION TRUST
RV5,SOUTH LONDON AND MAUDSLEY NHS FOUNDATION TRUST
RQY,SOUTH WEST LONDON AND ST GEORGE'S MENTAL HEALTH NHS TRUST
RXG,SOUTH WEST YORKSHIRE PARTNERSHIP NHS FOUNDATION TRUST
RW1,SOUTHERN HEALTH NHS FOUNDATION TRUST
NYA,ST ANDREW'S HEALTHCARE
8CM63,ST MAGNUS HOSPITAL
RX2,SUSSEX PARTNERSHIP NHS FOUNDATION TRUST
RNK,TAVISTOCK AND PORTMAN NHS FOUNDATION TRUST
RX3,"TEES, ESK AND WEAR VALLEYS NHS FOUNDATION TRUST"
NV2,THE HUNTERCOMBE GROUP
RKE,WHITTINGTON HOSPITAL NHS TRUST
RKL,WEST LONDON NHS TRUST"""
df = pd.read_csv(io.StringIO(data), header=0, delimiter=',').astype(str)
spark.createDataFrame(df).createOrReplaceGlobalTempView("restraints_exp_provider_list2")

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMP VIEW RESTRAINTS_PROVIDER_LIST AS
 select OrgCode, OrgName
 from global_temp.restraints_exp_provider_list2
 UNION
 select distinct a.orgidprov as OrgCode, od.NAME as OrgName
 from global_temp.RESTRAINTS_PERFORMANCE a
 LEFT JOIN $reference_data.ORG_DAILY as od
           ON COALESCE(a.orgidprov, 'UNKNOWN') = COALESCE(od.ORG_CODE, 'UNKNOWN') AND od.BUSINESS_END_DATE IS NULL
           AND od.ORG_OPEN_DATE <= '2021-03-31'
           AND ((od.ORG_CLOSE_DATE >= '2020-04-01') OR od.ORG_CLOSE_DATE is NULL)
 where a.uniqmonthid between 1441 and 1452
 order by OrgCode

# COMMAND ----------

 %sql
 -- Calculate the actual counts for each table
 CREATE OR REPLACE GLOBAL TEMPORARY VIEW TableCounts AS
 (
   SELECT 
     UniqMonthID,
     'MHS505RestrictiveIntervention' AS TableName,
     OrgIDProv,
     COUNT(*) AS RowCount
   FROM global_temp.RESTRAINTS_PERFORMANCE
   WHERE uniqmonthid = '$month_id'
   GROUP BY Uniqmonthid, OrgIDProv  
 )

# COMMAND ----------

 %sql
 CREATE OR REPLACE GLOBAL TEMPORARY VIEW restraints_dq_coverage_pre AS
 select
 '$rp_startdate' as REPORTING_PERIOD_START,
 '$rp_enddate' as REPORTING_PERIOD_END,
 'Performance' as STATUS,
 a.OrgCode as ORGANISATION_CODE,
 a.OrgName as ORGANISATION_NAME,
 COALESCE(b.TableName, 'MHS505RestrictiveIntervention') as TABLE_NAME,
 COALESCE(CAST(CASE WHEN b.RowCount < 5 THEN '99999' ELSE ROUND(b.RowCount/5, 0)*5 END as INT), '*') as COVERAGE_COUNT
 FROM global_temp.RESTRAINTS_PROVIDER_LIST a
 LEFT JOIN global_temp.TableCounts b ON a.OrgCode = b.OrgIDProv

# COMMAND ----------

 %sql
 insert into $db_output.dq_coverage_restraints
 select
 date_format(REPORTING_PERIOD_START,  "dd/MM/yyyy"),
 date_format(REPORTING_PERIOD_END,  "dd/MM/yyyy"),
 STATUS,
 ORGANISATION_CODE,
 ORGANISATION_NAME,
 TABLE_NAME,
 CAST(CASE WHEN COVERAGE_COUNT = 99999 THEN '*' ELSE COVERAGE_COUNT END as STRING) as COVERAGE_COUNT
 FROM global_temp.restraints_dq_coverage_pre

# COMMAND ----------

