-- Databricks notebook source


-- COMMAND ----------

 %sql

 INSERT OVERWRITE TABLE $db.dq_dimension_type
 VALUES (1, NULL, 'Coverage', 'Data coverage, in the context of HSCIC data quality assurance, is a measure of the degree to which data has been received from all expected sources. For example, if a data asset has been mandated for collection from all NHS-funded Mental Health Providers, then non-submission of the data by any one specific provider needs to be reported.'),
 (2, NULL, 'Completeness', 'Data completeness, in the context of HSCIC data quality assurance, is a measure of the degree to which data received is found to contain blank / null values.  **Not applicable to the MHSDS dataset. Blank / null values are currently reported under VODIM items (Valid, Other, Default, Invalid, Missing) as part of the Validity dimension.**'),
 (3, 'MHS-DQM', 'Validity', 'Single-field validation, in the context of HSCIC data quality assurance, is the degree to which data collected satisfies the set of business rules that govern the permitted values and formats for each individual field in a data asset. Single-field validation checks should, as a minimum, cover the permitted values and formats for each field in a data asset where those values and formats have been defined in approved data standards.'),
 (4, NULL, 'Consistency', 'Consistency, in the context of HSCIC data quality assurance, is a measure of the degree to which data can be compared over time and domain.'),
 (5, NULL, 'Uniqueness', 'Uniqueness, in the context of HSCIC data quality assurance, is a measure of the degree to which data excludes all duplicate records.'),
 (6, NULL, 'Punctuality', 'Punctuality, in the context of HSCIC data quality assurance, is a measure of the proximity between the date and time the HSCIC expects to receive data from data providers and the date and time it actually receives it.  **Not applicable to the MHSDS Dataset.**'),
 (7, 'MHS-DIM', 'Integrity', 'Integrity, in the context of HSCIC data quality assurance, is the degree to which data collected satisfies the set of business rules that govern the relationships between fields, records, activity types and data assets.  ');

 ANALYZE TABLE $db.dq_dimension_type COMPUTE STATISTICS FOR COLUMNS DimensionTypeId;

-- COMMAND ----------

 %sql
 -----------------------------------------------------------------------------------------------------------
 -- In the fraction 5/9, for example, the numerator is 5 (= DQ problem) 
 -- and the denominator is 9 (= total mental health referrals)
 -----------------------------------------------------------------------------------------------------------
 INSERT OVERWRITE TABLE $db.dq_measure_type
 VALUES (1, 'Denominator'),
   (2, 'Numerator');
   
 ANALYZE TABLE $db.dq_measure_type COMPUTE STATISTICS FOR COLUMNS MeasureTypeId;

 INSERT OVERWRITE TABLE $db.dq_metric_type
 VALUES (1, 3, 'Valid', 'The number of valid records.'),
 (2, 3, 'Other', 'The number of other records.'),
 (3, 3, 'Default', 'The number of default records.'),
 (4, 3, 'Invalid', 'The number of invalid records.'),
 (5, 3, 'Missing', 'The number of missing records.'),
 (1, 7, 'Integrity', NULL);

 ANALYZE TABLE $db.dq_metric_type COMPUTE STATISTICS FOR COLUMNS DimensionTypeId, MetricTypeId;

-- COMMAND ----------

 %sql

 INSERT OVERWRITE TABLE $db.dq_measure
 VALUES (1, 3, 'NHS Number', 'The presence of a valid NHS Number is tested using the NHS Number Flag.  ', 'NHS Number'),
 (2, 3, 'Postcode Of Usual Address', 'The presence of a valid Postcode is tested using the Postcode Flag.', 'Postcode'),
 (3, 3, 'Person Birth Date', 'Birth Date is tested using the Age at Reporting Period End Date.', 'Birth Date'),
 (4, 3, 'Person Stated Gender Code', 'Person Stated Gender is tested against the Person Stated Gender code list. ', 'Person Stated Gender Code'),
 (5, 3, 'Ethnic Category Code', 'The Persons Ethnic Category is tested against the Ethnic Category code list. (Only the first character is tested for the Valid and Other categories).', 'Ethnic Category'),
 (6, 3, 'General Medical Practice Code (Patient Registration)', 'The General Medical Practice code is tested against the ODS Current GP Practices table (Scottish GP Practices are not checked).', 'General Medical Practice Code (Patient Registration)'),
 (7, 3, 'Mental Health Act Legal Status Classification Code', 'The Legal Status Classification Code for each Mental Health Act Event is tested against the Legal Status Classification code list.', 'Legal Status Classification Code'),
 (8, 3, 'Treatment Function Code (Mental Health)', 'The Treatment Function from the inpatient record, is tested against a list of valid Treatment Functions.', 'Treatment Function Code (Mental Health)'),
 (9, 3, 'Organisation Site Identifier (Of Treatment)', 'The Organisation Site Identifier (Of Treatment) is tested for a valid format and against the ODS tables.', 'Organisation Site Identifier (Of Treatment)'),
 (10, 3, 'Primary Reason for Referral (Mental Health)', 'Primary Reason for Referral (Mental Health) is tested against the Primary Reason for Referral (Mental Health) code.', 'Primary Reason for Referral (Mental Health)'),
 (11, 3, 'Care Professional Service or Team Type Association (Mental Health)', 'Care Professional Service or Team Type Association (Mental Health) is tested against the Care Professional Service or Team Type Association (Mental Health) code.', 'Care Professional Service or Team Type Association (Mental Health)'),
 (12, 3, 'Organisation Identifier (Of Commissioner) - Referral', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Referral', 'Organisation Identifier (Of Commissioner)'),
 (13, 3, 'Organisation Identifier (Of Commissioner) - Contact', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Contact', 'Organisation Identifier (Of Commissioner)'),
 (14, 3, 'Organisation Identifier (Of Commissioner) - Indirect Activity', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Indirect Activity', 'Organisation Identifier (Of Commissioner)'),
 (15, 3, 'Organisation Identifier (Of Commissioner) - Group Session', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Group Session', 'Organisation Identifier (Of Commissioner)'),
 (16, 3, 'Organisation Identifier (Of Commissioner) - Hospital Provider Spell Commissioner', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Hospital Provider Spell Commissioner', 'Organisation Identifier (Of Commissioner)'),
 (17, 3, 'Organisation Identifier (Of Commissioner) - Anonymous Self-Assessment', 'The Organisation Identifier (Of Commissioner) is tested for a valid format and the first character is tested to ensure it represents a valid commissioner trust type - Anonymous Self-Assessment', 'Organisation Identifier (Of Commissioner)'),
 (18, 3, 'Service Or Team Type Referred To (Mental Health)', 'Service Or Team Type Referred To (Mental Health) is tested against the Service Or Team Type Referred To (Mental Health) code.', 'Service Or Team Type Referred To (Mental Health)'),
 (19, 3, 'Primary Reason for Referral (Mental Health) (Referral received on or after 1st Jan 2016)', 'Primary Reason for Referral (Mental Health) is tested against the Primary Reason for Referral (Mental Health) code. This is limited to referrals with a referral received date on or after 1st Jan 2016.', 'Primary Reason for Referral (Mental Health)'),
 (20, 3, 'Clinical Response Priority Type', 'Clinical Response Priority Type is tested against the Clinical Response Priority Type code list where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', 'Clinical Response Priority Type (Eating Disorder)'),
 (21, 3, 'Coded Procedure (Clinical Terminology Read Codes CTV2)', 'Procedure codes (Read codes CTV2) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Procedure (Clinical Terminology Read Codes CTV2)'),
 (22, 3, 'Coded Procedure (Clinical Terminology Read Codes CTV3)', 'Procedure codes (Read codes CTV3) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Procedure (Clinical Terminology Read Codes CTV3)'),
 (23, 3, 'Coded Procedure (Clinical Terminology Snomed CT)', 'Procedure codes (Snomed CT) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/snomed', 'Coded Procedure (Clinical Terminology Snomed CT)'),
 (24, 3, 'Coded Finding (Clinical Terminology Read Codes CTV2)', 'Finding codes (CTV2) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Finding (Clinical Terminology Read Codes CTV2)'),
 (25, 3, 'Coded Finding (Clinical Terminology Read Codes CTV3)', 'Finding codes (CTV3) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Finding (Clinical Terminology Read Codes CTV3)'),
 (26, 3, 'Coded Finding (Clinical Terminology ICD10)', 'Finding codes (ICD10 - Full stops, Daggers and Asterisks are removed) are tested against reference data available on the UK Clinical Classifications website http://systems.digital.nhs.uk/data/clinicalcoding/codingstandards/icd10/icd10updates', 'Coded Finding (Clinical Terminology ICD10)'),
 (27, 3, 'Coded Finding (Clinical Terminology Snomed CT)', 'Procedure codes (Snomed CT) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/snomed', 'Coded Finding (Clinical Terminology Snomed CT)'),
 (28, 3, 'Coded Observation (Clinical Terminology Read Codes CTV2)', 'Observation codes (CTV2) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Observation (Clinical Terminology Read Codes CTV2)'),
 (29, 3, 'Coded Observation (Clinical Terminology Read Codes CTV3)', 'Observation codes (CTV3) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/readcodes', 'Coded Observation (Clinical Terminology Read Codes CTV3)'),
 (30, 3, 'Coded Observation (Clinical Terminology Snomed CT)', 'Procedure codes (Snomed CT) are tested against reference data available on the UK Terminology website http://systems.digital.nhs.uk/data/uktc/snomed', 'Coded Observation (Clinical Terminology Snomed CT)'),
 (31, 3, 'Mental Health Admitted Patient Classification Type', 'Mental Health Admitted Patient Classification Type is tested against the Mental Health Admitted Patient Classification Type code list. This is limited to ward stays that started on or after 1st April 2017.', 'Mental Health Admitted Patient Classification Type'),
 (32, 3, 'Referred out of area reason (adult acute mental health)', 'Out of Area Treatment Reason is tested against the Out of Area Treatment code list', 'Referred out of area reason (adult acute mental health)'),
 (33, 3, 'Ex-British armed forces indicator', 'Ex-British armed forces indicator is testing against the Ex-British armed forces indicator code list', 'Ex-British armed forces indicator'),
 (34, 3, 'Source of Referral', 'Source of referral is tested against the source of referral codes list', 'Source of referral'),
 (35, 3, 'Consultation Mechanism (Mental Health)', 'Consultation Mechanism (Mental Health) is tested against the Consultation Mechanism (Mental Health) codes list', 'Consultation Mechanism (Mental Health)'),
 (37, 3, 'Activity location type code', 'Activity location type used is tested against the activity location type codes list', 'Activity location type code'),
 (38, 3, 'Clinically ready for discharge delay reason', 'Clinically ready for discharge delay reason used is tested against the Clinically ready for discharge delay reason codes list', 'Clinically ready for discharge delay reason'),
 (39, 3, 'Clinically Ready for Discharge Period attributable to', 'Clinically Ready for Discharge Period attributable to is tested against the Clinically Ready for Discharge Period attributable to indication code list', 'Clinically Ready for Discharge Period attributable to'),
 (42, 3, 'Care plan type', 'Care plan type used is tested against the care plan type codes list', 'Care plan type'),
 (45, 3, 'Provisional Diagnosis date', 'Provisional Diagnosis date is tested against the referral start date', 'Provisional Diagnosis date'),
 (46, 3, 'Primary Diagnosis date', 'Primary Diagnosis date is tested against the referral start date', 'Primary Diagnosis date'),
 (47, 3, 'Secondary Diagnosis date', 'Secondary Diagnosis date is tested against the referral start date', 'Secondary Diagnosis date'),
 (48, 3, 'Attended or did not attend', 'Attended or did not attend is tested against the attended or did not attend codes list', 'Attended or did not attend'),
 (51, 3, 'Referral closure reason', 'Referral closure reason is tested against the referral closure reason codes list', 'Referral closure reason'),
 (52, 3, 'Estimated discharge date', 'Estimated discharge date is tested against a blank field and the hospital spell start date', 'Estimated discharge date'),
 (53, 3, 'Specialised mental health service code - Referral', 'Specialised mental health service code is tested against the list of accepted SMH service category codes', 'Specialised mental health service code - Referral'),
 (54, 3, 'Specialised mental health service code - Contact', 'Specialised mental health service code is tested against the list of accepted SMH service category codes', 'Specialised mental health service code - Contact'),
 (55, 3, 'Specialised mental health service code - Ward Stay', 'Specialised mental health service code is tested against the list of accepted SMH service category codes', 'Specialised mental health service code - Ward Stay'),
 (56, 3, 'Delayed discharge; Local Authority of responsibility', 'Data quality measure to check Local Authority codes in the Delayed Discharge table are correct. This needs to be published for England and Provider level', 'Delayed discharge; Local Authority of responsibility'),
 (57,3,'Organisation Identifier (code of specialised responsible commissioner) - Referral','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Referral','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (58,3,'Organisation Identifier (code of specialised responsible commissioner) - Care Contact','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - CareContact','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (59,3,'Organisation Identifier (code of specialised responsible commissioner) - Indirect Activity','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Indirect Activity','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (60,3,'Organisation Identifier (code of specialised responsible commissioner) - Group Session','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Group Session','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (61,3,'Organisation Identifier (code of specialised responsible commissioner) - Hospital Provider Spell Commissioner Assignment Period','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Hospital Provider Spell Commissioner Assignment period','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (62,3,'Organisation Identifier (code of specialised responsible commissioner) - Exceptional Package of Care','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Exceptional Package of Care','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),
 (63,3,'Organisation Identifier (code of specialised responsible commissioner) - Anonymous Self-Assessment','The ORGANISATION IDENTIFIER (CODE OF COMMISSIONER) is tested for a valid format and the first character is tested to ensure it represents a valid specialised responsible commissioner trust type - Anonymous Self-Assessment','ORGANISATION IDENTIFIER (CODE OF COMMISSIONER)'),

 -- new measures from CDQA team - start
 (64,3,'Accommodation Type','Accommodation Type is tested against the Accommodation Type code list','Accommodation Type'),
 (65,3,'Employment Status','Employment Status is tested against the Employment Status code list','Employment Status'),
 (66,3,'Disibility Code','Disibility Code is tested against the Disibility Code code list','Disibility Code'),
 (67,3,'Decided to Admit Date','Decided to Admit Date is tested against the referral start date','Decided to Admit Date'),
 (68,3,'Decided to Admit Time','Decided to Admit Date is tested against the referral start time','Decided to Admit Time'),
 (69,3,'Admission Source (Mental Health Provider Spell)','Admission Source (Mental Health Provider Spell) is tested against the Admission Source (Mental Health Provider Spell) code list','Admission Source (Mental Health Provider Spell)'),
 (70,3,'Destination Of Discharge (Hospital Provider Spell)','Destination Of Discharge (Hospital Provider Spell) is tested against the Destination Of Discharge (Hospital Provider Spell) code list','Destination Of Discharge (Hospital Provider Spell)'),
 (71,3,'Start Time (Restrictive Intervention Incident)','Start Time (Restrictive Intervention Incident) is tested against the referral start time','Start Time (Restrictive Intervention Incident)'),
 (72,3,'Restrictive Intervention Reason','Restrictive Intervention Reason is tested against the Restrictive Intervention Reason code list','Restrictive Intervention Reason'),
 (73,3,'Start Time (Restrictive Intervention Type)','Start Time (Restrictive Intervention Type) is tested against the referral start time','Start Time (Restrictive Intervention Type)'),
 (74,3,'Restrictive Intervention Type','Restrictive Intervention Type is tested against the Restrictive Intervention Type code list','Restrictive Intervention Type'),
 (75,3,'Ward Setting Type (Mental Health)','Ward Setting Type (Mental Health) is tested against the Ward Setting Type (Mental Health) code list','Ward Setting Type (Mental Health)'),
 (76,3,'Intended Age Group (Mental Health)','Intended Age Group (Mental Health) is tested against the Intended Age Group (Mental Health) code list','Intended Age Group (Mental Health)'),
 (77,3,'Sex Of Patients Code (Mental Health)','Sex Of Patients Code (Mental Health) is tested against the Sex Of Patients Code (Mental Health) code list','Sex Of Patients Code (Mental Health)'),
 (78,3,'Intended Clinical Care Intensity Code (Mental Health)','Intended Clinical Care Intensity Code (Mental Health) is tested against the Intended Clinical Care Intensity Code (Mental Health) code list','Intended Clinical Care Intensity Code (Mental Health)'),
 (79,3,'Ward Security Level','Ward Security Level is tested against the Ward Security Level code list','Ward Security Level'),
 (80,3,'Locked Ward Indicator','Locked Ward Indicator is tested against the Locked Ward Indicator code list','Locked Ward Indicator'),
 -- new measures from CDQA team - end
 (81, 3,'Gender Identity Code' ,'Gender Identity Code is tested against the Gender Identity Code list.','Gender Identity Code'),
 (82, 3,'Gender Identity Same At Birth Indicator Code', 'Gender Identity Same At Birth Indicator Code is tested against the Gender Identity Same At Birth Indicator Code list.','Gender Identity Same At Birth Indicator Code'),

 (1, 7, 'Referrals to CYP-MH services starting in RP', 'The number of Service or Team Referrals where the Referral Request Received Date is in the reporting period and service area is CYP-MH', 'Referrals to CYP-MH services starting in RP'),
 (2, 7, 'Referrals to Eating Disorder services starting in RP', 'The number of Referrals where the Referral Request Received Date is in the reporting period, Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', 'Referrals to Eating Disorder services starting in RP'),
 (3, 7, 'Coded Procedure (SNOMED Stop Clock for ED)', 'The number of SNOMED stop clock codes recorded in Procedure code for Eating Disorder referrals where Age at Service Referral Received Date is under 19', 'Coded Procedure (SNOMED Stop Clock for ED)'),
 (4, 7, 'Care contact time (Hour)', 'Care contact time is tested for a recording on the hour', 'Care contact time (Hour)'),
 (5, 7, 'Care contact time (Midnight)', 'Care contact time is tested for a recording at midnight', 'Care contact time (Midnight)'),
 (6, 7, 'Onward referral time (Hour)', 'Onward referral time is tested for a recording on the hour', 'Onward referral time (Hour)'),
 (7, 7, 'Onward referral time (Midnight)', 'Onward referral time is tested for a recording at midnight', 'Onward referral time (Midnight)'),
 (8, 7, 'Indirect activity time (Hour)', 'Indirect activity time is tested for a recording on the hour', 'Indirect activity time (Hour)'),
 (9, 7, 'Indirect activity time (Midnight)', 'Indirect activity time is tested for a recording at midnight', 'Indirect activity time (Midnight)'),
 (10, 7, 'Discharge plan creation time (Hour)', 'Discharge plan creation time is tested for a recording on the hour', 'Discharge plan creation time (Hour)'),
 (11, 7, 'Discharge plan creation time (Midnight)', 'Discharge plan creation time is tested for a recording at midnight', 'Discharge plan creation time (Midnight)'),
 (12, 7, 'Referral request received time (Hour)', 'Referral request received time is tested for a recording on the hour', 'Referral request received time (Hour)'),
 (13, 7, 'Referral request received time (Midnight)', 'Referral request received time is tested for a recording at midnight', 'Referral request received time (Midnight)'),
 (14, 7, 'Service discharge time (Hour)', 'Service discharge time is tested for a recording on the hour', 'Service discharge time (Hour)'),
 (15, 7, 'Service discharge time (Midnight)', 'Service discharge time is tested for a recording at midnight', 'Service dischared time (Midnight)'),
 -- new measures for MHA
 (16, 7, 'Mental Health Act - Ethnicity recording', 'Mental Health Act record is tested for missing or invalid ethnicity', 'Mental Health Act - Ethnicity recording'),
 (17, 7, 'Mental Health Act - Start time (Midnight)', 'Start Time (Mental Health Act Legal Status Classification Assignment Period) is tested for a recording at midnight', 'Start Time - Mental Health Act Legal Status Classification Assignment Period (Midnight)'),
 (18, 7, 'Mental Health Act - Start time (Midday)', 'Start Time (Mental Health Act Legal Status Classification Assignment Period) is tested for a recording at midday', 'Start Time - Mental Health Act Legal Status Classification Assignment Period (Midday)'),
 (19, 7, 'Mental Health Act - Start time (Hour)', 'Start Time (Mental Health Act Legal Status Classification Assignment Period) is tested for a recording on the hour', 'Start Time - Mental Health Act Legal Status Classification Assignment Period (Hour)'),
 (20, 7, 'Mental Health Act - episodes becoming inactive', 'The number of Mental Health Act Legal Status Classification Assignment Period records from previous reporting period becoming inactive in the current reporing period', 'End Date (Mental Health Act Legal Status Classification Assignment Period)');

 ANALYZE TABLE $db.dq_measure COMPUTE STATISTICS FOR COLUMNS DimensionTypeId, MeasureId;

-- COMMAND ----------

 %sql

 INSERT OVERWRITE TABLE $db.dq_measure_description
 VALUES (1, 3, 1, NULL, 'All MHS001MPI records.', '2016-01-01', NULL),
 (1, 3, 2, 1, 'Records where the NHS Number Flag equals Y.', '2016-01-01', NULL),
 (1, 3, 2, 5, 'Records where the NHS Number flag equals N.', '2016-01-01', NULL),
 (2, 3, 1, NULL, 'All MHS001MPI records.', '2016-01-01', NULL),
 (2, 3, 2, 1, 'Records where the Postcode Flag equals Y.', '2016-01-01', NULL),
 (2, 3, 2, 3, 'Records where the DefaultPostcode field starts with ZZ99', '2016-08-01', NULL),
 (2, 3, 2, 5, 'Records where the Postcode Flag equals N. ', '2016-01-01', NULL),
 (3, 3, 1, NULL, 'All MHS001MPI records.', '2016-01-01', NULL),
 (3, 3, 2, 1, 'Records where the Age at Reporting Period End Date is below or equal to 120. ', '2016-01-01', NULL),
 (3, 3, 2, 4, 'Records where the Age at Reporting Period End Date is greater than 120 and where the Age at Reporting Period End Date is not missing.', '2016-01-01', NULL),
 (3, 3, 2, 5, 'Records with no Age at Reporting Period End Date. ', '2016-01-01', NULL),
 (4, 3, 1, NULL, 'All MHS001MPI records.', '2016-01-01', NULL),
 (4, 3, 2, 1, 'Records with a Person Stated Gender code 1 or 2.', '2016-01-01', NULL),
 (4, 3, 2, 2, 'Records with a Person Stated Gender code 9.', '2016-01-01', NULL),
 (4, 3, 2, 3, 'Records with a Person Stated Gender code X.', '2016-01-01', NULL),
 (4, 3, 2, 4, 'Records with a Person Stated Gender code not X, 1, 2, 9 and not missing.', '2016-01-01', NULL),
 (4, 3, 2, 5, 'Records with no Person Stated Gender code.', '2016-01-01', NULL),
 (5, 3, 1, NULL, 'All MHS001MPI records.', '2016-01-01', NULL),
 (5, 3, 2, 1, 'Records where the first character of the Persons Ethnic Category equals A-H, J-N, P, R or S.', '2016-01-01', NULL),
 (5, 3, 2, 2, 'Records where the first character of the Persons Ethnic Category equals to Z.', '2016-01-01', NULL),
 (5, 3, 2, 3, 'Records with a Persons Ethnic Category 99.', '2016-01-01', NULL),
 (5, 3, 2, 4, 'Records where the first character of the Persons Ethnic Category does not equal A-H, J-N, P, R, S, Z, where the Persons Ethnic Category is not equal to 99 and where the Persons Ethnic Category is not missing.', '2016-01-01', NULL),
 (5, 3, 2, 5, 'Records with no Persons Ethnic Category.', '2016-01-01', NULL),
 (6, 3, 1, NULL, 'All MHS002GP records, except those where the  General Medical Practice Code starts with an S (representing Scottish Practices).', '2016-01-01', NULL),
 (6, 3, 2, 1, 'Records with a General Medical Practice code (not equal to V81999, V81998 or V81997) that could be matched to a GP Practice in the ODS Current GP Practices table, which was still open at the end of the reporting period. ', '2016-01-01', NULL),
 (6, 3, 2, 2, 'Records with a  General Medical Practice code (not equal to V81999, V81998 or V81997) that could be matched to a GP Practice in the ODS Current GP Practices table, which was closed during or one day before the start of the reporting period. ', '2016-01-01', NULL),
 (6, 3, 2, 3, 'Records with a  General Medical Practice code equal to V81999, V81998 or V81997.', '2016-01-01', NULL),
 (6, 3, 2, 4, 'Records with a Practice code (not equal to V81999, V81998 or V81997) that could not be matched to a Practice in the ODS table or which was matched to a Practice which was closed before the day before the start of the period. The code must not be missing', '2016-01-01', NULL),
 (7, 3, 1, NULL, 'All MHS401MHActPeriod records.', '2016-01-01', NULL),
 (7, 3, 2, 1, 'Records with a Legal Status Classification Code 02-10, 12-20, 31,32, 35, 36, 37 or 38.', '2016-01-01', NULL),
 (7, 3, 2, 2, 'Records with a Legal Status Classification Code 01. ', '2016-01-01', NULL),
 (7, 3, 2, 3, 'Records with a Legal Status Classification Code of 98 or 99.', '2016-01-01', NULL),
 (7, 3, 2, 4, 'Records with a Legal Status Classification Code not (01-10, 12-20, 31, 32, 35, 36, 37, 38, 98, 99 or missing).', '2016-01-01', NULL),
 (7, 3, 2, 5, 'Records with no Legal Status Classification Code.', '2016-01-01', NULL),
 (8, 3, 1, NULL, 'All MHS503AssignedCareProf records.', '2016-01-01', NULL),
 (8, 3, 2, 1, 'Records with a Treatment Function 700, 710, 711, 712, 713, 715, 720, 721, 722, 723, 724, 725, 726, 727.', '2016-01-01', NULL),
 (8, 3, 2, 4, 'Records where value could not be matched against a list of Treatment Function Codes and where value is not missing.', '2016-01-01', NULL),
 (8, 3, 2, 5, 'Records with no Treatment Function.', '2016-01-01', NULL),
 (9, 3, 1, NULL, 'All MHS502WardStay records.', '2016-01-01', NULL),
 (9, 3, 2, 1, 'Records with an Organisation Site Identifier (Of Treatment) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (9, 3, 2, 2, 'Records with an Organisation Site Identifier (Of Treatment) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (9, 3, 2, 3, 'Records with an Organisation Site Identifier (Of Treatment) of R9998, 89997 or 89999', '2016-01-01', NULL),
 (9, 3, 2, 4, 'Records with an Org Site Identifier (Of Treatment) not  matched to an Org Identifier in the ODS Organisational tables or could be matched to an Identifier which was closed beforethe day before the start of the period. The Identifier must not be missing', '2016-01-01', NULL),
 (9, 3, 2, 5, 'Records with no Organisation Site Identifier (Of Treatment) .', '2016-01-01', NULL),
 (10, 3, 1, NULL, 'All MHS101Referral records.', '2016-01-01', NULL),
 (10, 3, 2, 1, 'Records with a Primary Reason for Referral (Mental Health) code 01 - 16, 18-27.', '2016-01-01', NULL),
 (10, 3, 2, 4, 'Records with a Primary Reason for Referral (Mental Health) code not 01 - 16, 18-27 and not missing.', '2016-01-01', NULL),
 (10, 3, 2, 5, 'Records with no Primary Reason for Referral (Mental Health) code.', '2016-01-01', NULL),
 (11, 3, 1, NULL, 'All MHS006MHCareCoord records.', '2016-04-01', NULL),
 (11, 3, 2, 1, 'Records with a Care Professional Service or Team Type Association (Mental Health) code A01 - A18, A20, B01, B02, C01 - C09, D01 - D05, E01 - E04.', '2016-04-01', NULL),
 (11, 3, 2, 2, 'Records with a Care Professional Service or Team Type Association (Mental Health) code Z01 or Z02.', '2016-04-01', NULL),
 (11, 3, 2, 4, 'Records with a Care Professional Service or Team Type Association (Mental Health) code not (A01 - A18, A20, B01, B02, C01 - C09, D01 - D05, E01 - E04, Z01, Z02 or missing)', '2016-04-01', NULL),
 (11, 3, 2, 5, 'Records with no Care Professional Service or Team Type Association (Mental Health) code.', '2016-04-01', NULL),
 (12, 3, 1, NULL, 'All MHS101Referral records.', '2016-01-01', NULL),
 (12, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (12, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (12, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (12, 3, 2, 4, 'Records with an Org Identifier (of Commissioner) not matched to an Org Identifier in the ODS Organisational tables,  or matched to an Organisation Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (13, 3, 1, NULL, 'All MHS201CareContact records.', '2016-01-01', NULL),
 (13, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (13, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (13, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (13, 3, 2, 4, 'Records with an Org Identifier (of Commissioner) not matched to an Org Identifier in the ODS Organisational tables,  or matched to an Org Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (13, 3, 2, 5, 'Records with no Organisation Identifier (Of Commissioner).', '2016-01-01', NULL),
 (14, 3, 1, NULL, 'All MHS204IndirectActivity records.', '2016-01-01', NULL),
 (14, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (14, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (14, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (14, 3, 2, 4, 'Records with an Org Identifier (Of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables,  or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (14, 3, 2, 5, 'Records with no Organisation Identifier (Of Commissioner).', '2016-01-01', NULL),
 (15, 3, 1, NULL, 'All MHS301GroupSession records.', '2016-01-01', NULL),
 (15, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (15, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (15, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (15, 3, 2, 4, 'Records with an Org Identifier (Of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables,  or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (16, 3, 1, NULL, 'All MHS512HospSpellComm records.', '2016-01-01', NULL),
 (16, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (16, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (16, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (16, 3, 2, 4, 'Records with an Org Identifier (Of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables,  or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (17, 3, 1, NULL, 'All MHS608AnonSelfAssess records.', '2016-01-01', NULL),
 (17, 3, 2, 1, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was still open at the end of the reporting period.', '2016-01-01', NULL),
 (17, 3, 2, 2, 'Records with an Organisation Identifier (Of Commissioner) that could be matched to an Organisation Identifier in the ODS Organisational tables, which was closed during or one day before the start of the reporting period.', '2016-01-01', NULL),
 (17, 3, 2, 3, 'Records with an Organisation Identifier (Of Commissioner) equal to VPP00 or XMD00 or YDD82', '2016-08-01', NULL),
 (17, 3, 2, 4, 'Records with an Org Identifier (Of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables,  or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.', '2016-01-01', NULL),
 (17, 3, 2, 5, 'Records with no Organisation Identifier (Of Commissioner).', '2016-01-01', NULL),
 (18, 3, 1, NULL, 'All MHS102ServiceTypeReferredTo records.', '2016-04-01', NULL),
 (18, 3, 2, 1, 'Records with a Service Or Team Type Referred To (Mental Health) code A01 - A18, A20, B01, B02, C01 - C09, D01 - D05, E01 - E04.', '2016-04-01', NULL),
 (18, 3, 2, 2, 'Records with a Service Or Team Type Referred To (Mental Health) code Z01 or Z02.', '2016-04-01', NULL),
 (18, 3, 2, 4, 'Records with a Service Or Team Type Referred To (Mental Health) code not (A01 - A18, A20, B01, B02, C01 - C09, D01 - D05, E01 - E04, Z01, Z02 or missing)', '2016-04-01', NULL),
 (18, 3, 2, 5, 'Records with no Service Or Team Type Referred To (Mental Health) code.', '2016-04-01', NULL),
 (19, 3, 1, NULL, 'All MHS101Referral records where referral received date >= ''01/01/16''', '2016-08-01', NULL),
 (19, 3, 2, 1, 'Records with a Primary Reason for Referral (Mental Health) code 01 - 16, 18-27 and referral received date >= 01/01/16', '2016-08-01', NULL),
 (19, 3, 2, 4, 'Records with a Primary Reason for Referral (Mental Health) code not 01 - 16, 18-27 and not missing and referral received date >= 01/01/16', '2016-08-01', NULL),
 (19, 3, 2, 5, 'Records with no Primary Reason for Referral (Mental Health) code and referral received date >= ''01/01/16''', '2016-08-01', NULL),
 (20, 3, 1, NULL, 'All referrals where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (20, 3, 2, 1, 'Number of records with a Clinical Response Priority Type Code 1, 2, 3 and where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (20, 3, 2, 4, 'Number of records with a Clinical Response Priority Type Code that does not equal 1, 2 or 3 and is not null and where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (20, 3, 2, 5, 'Number of records with no Clinical Response Priority Type Code recorded and where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (21, 3, 1, NULL, 'All records with procedure scheme ''04'' recorded', '2016-08-01', NULL),
 (21, 3, 2, 1, 'Number of Procedure Codes (Read codes CTV2) recorded, matched against reference data and active during period and procedure scheme ''04'' recorded', '2016-08-01', NULL),
 (21, 3, 2, 4, 'Number of Procedure Codes (Read Codes CTV2) recorded and not matched against reference data or matched but code inactive during period and procedure scheme ''04'' recorded', '2016-08-01', NULL),
 (21, 3, 2, 5, 'Number of records with no code recorded and procedure scheme ''04'' recorded', '2016-08-01', NULL),
 (22, 3, 1, NULL, 'All records with procedure scheme ''05'' recorded', '2016-08-01', NULL),
 (22, 3, 2, 1, 'Number of Procedure Codes (Read Codes CTV3) recorded, matched against reference data and open during period and procedure scheme ''05'' recorded', '2016-08-01', NULL),
 (22, 3, 2, 4, 'Number of Procedure Codes (Read Codes CTV3) recorded and not matched against reference data or matched but code closed during period and procedure scheme ''05'' recorded', '2016-08-01', NULL),
 (22, 3, 2, 5, 'Number of records with no code recorded and procedure scheme ''05'' recorded', '2016-08-01', NULL),
 (23, 3, 1, NULL, 'All records with procedure scheme ''06'' recorded', '2016-08-01', NULL),
 (23, 3, 2, 1, 'Number of Procedure Codes (Snomed CT) recorded, matched against reference data and open during period and procedure scheme ''06'' recorded', '2016-08-01', NULL),
 (23, 3, 2, 4, 'Number of Procedure Codes (Snomed CT) recorded, not matched against reference data or matched but closed during period and procedure scheme ''06'' recorded', '2016-08-01', NULL),
 (23, 3, 2, 5, 'Number of records with no code recorded and procedure scheme ''06'' recorded', '2016-08-01', NULL),
 (24, 3, 1, NULL, 'All records with finding scheme ''02'' recorded', '2016-08-01', NULL),
 (24, 3, 2, 1, 'Number of Finding Codes (CTV2) recorded, matched against reference data and open during period and finding scheme ''02'' recorded', '2016-08-01', NULL),
 (24, 3, 2, 4, 'Number of Finding Codes (CTV2) recorded and not matched against reference data or matched but code closed during period and finding scheme ''02'' recorded', '2016-08-01', NULL),
 (24, 3, 2, 5, 'Number of records with no code recorded and finding scheme ''02'' recorded', '2016-08-01', NULL),
 (25, 3, 1, NULL, 'All records with finding scheme ''03'' recorded', '2016-08-01', NULL),
 (25, 3, 2, 1, 'Number of Finding Codes (CTV3) recorded, matched against reference data and open during period and finding scheme ''03'' recorded', '2016-08-01', NULL),
 (25, 3, 2, 4, 'Number of Finding Codes (CTV3) recorded and not matched against reference data or matched but code closed during period and finding scheme ''03'' recorded', '2016-08-01', NULL),
 (25, 3, 2, 5, 'Number of records with no code recorded and finding scheme ''03'' recorded', '2016-08-01', NULL),
 (26, 3, 1, NULL, 'All records with finding scheme ''01'' recorded', '2016-08-01', NULL),
 (26, 3, 2, 1, 'Number of Finding Codes (ICD10) recorded and matched against reference data and finding scheme ''01'' recorded', '2016-08-01', NULL),
 (26, 3, 2, 4, 'Number of Finding Codes (ICD10) recorded and not matched against reference data and finding scheme ''01'' recorded', '2016-08-01', NULL),
 (26, 3, 2, 5, 'Number of records with no code recorded and finding scheme ''01'' recorded', '2016-08-01', NULL),
 (27, 3, 1, NULL, 'All records with Finding scheme ''04'' recorded', '2016-08-01', NULL),
 (27, 3, 2, 1, 'Number of Finding Codes (Snomed CT) recorded, matched against reference data and open during period and Finding scheme ''04'' recorded', '2016-08-01', NULL),
 (27, 3, 2, 4, 'Number of Finding Codes (Snomed CT) recorded, not matched against reference data or matched but closed during period and Finding scheme ''04'' recorded', '2016-08-01', NULL),
 (27, 3, 2, 5, 'Number of records with no code recorded and Finding scheme ''04'' recorded', '2016-08-01', NULL),
 (28, 3, 1, NULL, 'All records with observation scheme ''01'' recorded', '2016-08-01', NULL),
 (28, 3, 2, 1, 'Number of Observation Codes (CTV2) recorded, matched against reference data and open during period and observation scheme ''01'' recorded', '2016-08-01', NULL),
 (28, 3, 2, 4, 'Number of Observation Codes (CTV2) recorded and not matched against reference data or matched but code closed during period and observation scheme ''01'' recorded', '2016-08-01', NULL),
 (28, 3, 2, 5, 'Number of records with no code recorded and observation scheme ''01'' recorded', '2016-08-01', NULL),
 (29, 3, 1, NULL, 'All records with observation scheme ''02'' recorded', '2016-08-01', NULL),
 (29, 3, 2, 1, 'Number of Observation Codes (CTV3) recorded, matched against reference data and open during period and observation scheme ''02'' recorded', '2016-08-01', NULL),
 (29, 3, 2, 4, 'Number of Observation Codes (CTV3) recorded and not matched against reference data or matched but code closed during period and observation scheme ''02'' recorded', '2016-08-01', NULL),
 (29, 3, 2, 5, 'Number of records with no code recorded and observation scheme ''02'' recorded', '2016-08-01', NULL),
 (30, 3, 1, NULL, 'All records with Observation scheme ''03'' recorded', '2016-08-01', NULL),
 (30, 3, 2, 1, 'Number of Observation Codes (Snomed CT) recorded, matched against reference data and open during period and Observation scheme ''03'' recorded', '2016-08-01', NULL),
 (30, 3, 2, 4, 'Number of Observation Codes (Snomed CT) recorded, not matched against reference data or matched but closed during period and Observation scheme ''03'' recorded', '2016-08-01', NULL),
 (30, 3, 2, 5, 'Number of records with no code recorded and Observation scheme ''03'' recorded', '2016-08-01', NULL),
 (31, 3, 1, NULL, 'All MHS502WardStay records where Start Date >=  01/04/17 ', '2018-04-01', NULL),
 (31, 3, 2, 1, 'Records with a Hospital Bed Type (Mental Health) code 10 - 34 and Start Date >=  01/04/17 ', '2018-04-01', NULL),
 (31, 3, 2, 4, 'Records with a Hospital Bed Type (Mental Health) code not in 10 - 34 and not NULL and Start Date >=  01/04/17 ', '2018-04-01', NULL),
 (31, 3, 2, 5, 'Records with no Hospital Bed Type (Mental Health) code and Start Date >=  01/04/17 ', '2018-04-01', NULL),
 (32, 3, 1, NULL, 'All non-NULL Referred out of area reason (adult acute mental health) records in MHS105ONwardReferral ', '2018-04-01', NULL),
 (32, 3, 2, 1, 'Records with a Referred out of area reason (adult acute mental health) code 10 - 14', '2018-04-01', NULL),
 (32, 3, 2, 3, 'Records with a Referred out of area reason (adult acute mental health) code 99', '2018-04-01', NULL),
 (32, 3, 2, 4, 'Records with a Referred out of area reason (adult acute mental health) code NOT IN 10-14 or 99', '2018-04-01', NULL),
 (33, 3, 1, NULL, 'All MHS005PatientIndicator records.', '2018-04-01', NULL),
 (33, 3, 2, 1, 'Records with a Ex-British armed forces indicator code 02  03 or 05', '2018-04-01', NULL),
 (33, 3, 2, 3, 'Records with a Ex-British armed forces indicator code UU or ZZ', '2018-04-01', NULL),
 (33, 3, 2, 4, 'Records with a Ex-British armed forces indicator code NOT IN 02  03  05  UU or ZZ', '2018-04-01', NULL),
 (33, 3, 2, 5, 'Records with no Ex-British armed forces indicator code', '2018-04-01', NULL),
 (34, 3, 1, NULL, 'All MHS101Referral records.', '2018-04-01', NULL),
 (34, 3, 2, 1, 'Records with a source of referral of A1-A4, B1-B2, C1-C3, D1-D2, E1-E5, F1-F3, G1-G4, H1-H2, I1-I2, M1-M7, N3, P1', '2018-04-01', NULL),
 (34, 3, 2, 4, 'Records with a source of referral not A1-A4, B1-B2, C1-C3, D1-D2, E1-E5, F1-F3, G1-G4, H1-H2, I1-I2, M1-M7, N3, P1 and not missing', '2018-04-01', NULL),
 (34, 3, 2, 5, 'Records with no source of referral code', '2018-04-01', NULL),
 (35, 3, 1, NULL, 'All MHS201CareContact records.', '2018-04-01', NULL),
 (35, 3, 2, 1, 'Records with a consultation Mechanism (Mental Health) code of 01-06 ', '2018-04-01', NULL),
 (35, 3, 2, 2, 'Records with a consultation Mechanism (Mental Health) code of 98', '2018-04-01', NULL),
 (35, 3, 2, 4, 'Records with a consultation Mechanism (Mental Health) code not 01-06 or 98 and not missing', '2018-04-01', NULL),
 (35, 3, 2, 5, 'Records with no consultation Mechanism (Mental Health) code', '2018-04-01', NULL),
 (37, 3, 1, NULL, 'All MHS201CareContact records.', '2018-04-01', NULL),
 (37, 3, 2, 1, 'Records with an activity location type code of A01-A04, B01-B02, C01-C03, D01-D03, E01-E04, E99, F01, G01-G04, H01, J01, K01-K02, L01-L06, L99, M01-M05, N01-N05', '2018-04-01', NULL),
 (37, 3, 2, 2, 'Records with an activity location type code of X01', '2018-04-01', NULL),
 (37, 3, 2, 4, 'Records with an activity location type code not A01-A04, B01-B02, C01-C03, D01-D03, E01-E04, E99, F01, G01-G04, H01, J01, K01-K02, L01-L06, L99, M01-M-5, N01-N05, X01 and not missing', '2018-04-01', NULL),
 (37, 3, 2, 5, 'Records with no activity location type code', '2018-04-01', NULL),
 (38, 3, 1, NULL, 'All MHS504DelayedDischarge records.', '2018-04-01', NULL),
 (38, 3, 2, 1, 'Records with a delayed discharge reason code of A2, B1, C1, D1-D2, E1, F2, G2-G12, H1, I2-I3, J2, K2, L1, M1, N1', '2018-04-01', NULL),
 (38, 3, 2, 2, 'Records with a delayed discharge reason code of 98', '2018-04-01', NULL),
 (38, 3, 2, 4, 'Records with a dleayed discharge reason code not A2, B1, C1, D1-D2, E1, F2, G2-G12, H1, I2-I3, J2, K2, L1, M1, N1 and not missing', '2018-04-01', NULL),
 (38, 3, 2, 5, 'Records with no delayed discharge reason code', '2018-04-01', NULL),
 (39, 3, 1, NULL, 'All MHS504DelayedDischarge records.', '2018-04-01', NULL),
 (39, 3, 2, 1, 'Records with delayed discharge attributable to indication code of 04-07', '2018-04-01', NULL),
 (39, 3, 2, 4, 'Records with delayed discharge attributable to not code of 04-07 and not missing', '2018-04-01', NULL),
 (39, 3, 2, 5, 'Records with no delayed discharge attributable indication code', '2018-04-01', NULL),
 (42, 3, 1, NULL, 'All MHS008CarePlanType records.', '2018-04-01', NULL),
 (42, 3, 2, 1, 'Records with a care plan type code 10-14', '2018-04-01', NULL),
 (42, 3, 2, 4, 'Records with a care plan type code not 10-14', '2018-04-01', NULL),
 (45, 3, 1, NULL, 'All MHS603ProvDiag records.', '2018-04-01', NULL),
 (45, 3, 2, 1, 'Records with a valid diagnosis where 1) the Provisional Diagnosis date is between referral start and end dates or 2) the Provisional Diagnosis date is on or after referral start date if referral end date is null', '2018-04-01', NULL),
 (45, 3, 2, 4, 'Records with a valid Diagnosis where 1) the Provisional Diagnosis date is before referral start date or after end date OR 2) the Provisional Diagnosis date is before referral start date if referral end date is null', '2018-04-01', NULL),
 (45, 3, 2, 5, 'Records with no Provisional Diagnosis date', '2018-04-01', NULL),
 (46, 3, 1, NULL, 'All MHS604PrimDiag records.', '2018-04-01', NULL),
 (46, 3, 2, 1, 'Records with a valid diagnosis where 1) the Primary Diagnosis date is between referral start and end dates or 2) the Primary Diagnosis date is on or after referral start date if referral end date is null', '2018-04-01', NULL),
 (46, 3, 2, 4, 'Records with a valid Diagnosis where 1) the Primary Diagnosis date is before referral start date or after end date OR 2) the Primary Diagnosis date is before referral start date if referral end date is null', '2018-04-01', NULL),
 (46, 3, 2, 5, 'Records with no Primary Diagnosis date', '2018-04-01', NULL),
 (47, 3, 1, NULL, 'All MHS605SecDiag records.', '2018-04-01', NULL),
 (47, 3, 2, 1, 'Records with a valid diagnosis where 1) the Secondary Diagnosis date is between referral start and end dates or 2) the Secondary Diagnosis date is on or after referral start date if referral end date is null', '2018-04-01', NULL),
 (47, 3, 2, 4, 'Records with a valid Diagnosis where 1) the Secondary Diagnosis date is before referral start date or after end date OR 2) the Secondary Diagnosis date is before referral start date if referral end date is null', '2018-04-01', NULL),
 (47, 3, 2, 5, 'Records with no Secondary Diagnosis date', '2018-04-01', NULL),
 (48, 3, 1, NULL, 'All MHS201CareContact records.', '2018-04-01', NULL),
 (48, 3, 2, 1, 'Records with an attend or did not attend code of 2-7', '2018-04-01', NULL),
 (48, 3, 2, 4, 'Records with an attended or did not attend code not 2-7 and not missing', '2018-04-01', NULL),
 (48, 3, 2, 5, 'Records with no attend or did not attend code', '2018-04-01', NULL),
 (51, 3, 1, NULL, 'All MHS102ServiceTypeReferredTo records with a closure date', '2018-04-01', NULL),
 (51, 3, 2, 1, 'Records with a referral closure reason code 01-09', '2018-04-01', NULL),
 (51, 3, 2, 4, 'Records with a referral closure reason code not 01-09 and not missing', '2018-04-01', NULL),
 (51, 3, 2, 5, 'Records with no referral closure reason code', '2018-04-01', NULL),
 (52, 3, 1, NULL, 'All MHS501HospProvSpell records.', '2018-04-01', NULL),
 (52, 3, 2, 1, 'Records with a valid estimated discharge date date which is on or after the hospital spell start date', '2018-04-01', NULL),
 (52, 3, 2, 4, 'Records with a valid estimated discharge date date which is before the hospital spell start date', '2018-04-01', NULL),
 (52, 3, 2, 5, 'Records with no estimated discharge date', '2018-04-01', NULL),
 (53, 3, 1, NULL, 'All MHS101Referral records with a completed specialised mental health service code', '2019-02-01', NULL),
 (53, 3, 2, 1, 'Records with a valid SMH service category code', '2019-02-01', NULL),
 (53, 3, 2, 4, 'Records that contain an invalid SMH service category code', '2019-02-01', NULL),
 (54, 3, 1, NULL, 'All MHS101Referral records with a completed specialised mental health service code', '2019-02-01', NULL),
 (54, 3, 2, 1, 'Records with a valid SMH service category code', '2019-02-01', NULL),
 (54, 3, 2, 4, 'Records that contain an invalid SMH service category code', '2019-02-01', NULL),
 (55, 3, 1, NULL, 'All MHS502WardStay records with a completed specialised mental health service code.', '2019-02-01', NULL),
 (55, 3, 2, 1, 'Records with a valid SMH service category code', '2019-02-01', NULL),
 (55, 3, 2, 4, 'Records that contain an invalid SMH service category code', '2019-02-01', NULL),
 (56, 3, 1, NULL, 'All MHS504delayeddischarge records with a Local Authority of responsibility code.', '2019-02-01', NULL),
 (56, 3, 2, 1, 'Records that contain a valid Local Authority of responsibility code', '2019-02-01', NULL),
 (56, 3, 2, 4, 'Records that contain an invalid Local Authority of responsibility code', '2019-02-01', NULL),
 (56, 3, 2, 5, 'Records with no Local Authority of responsibility code', '2019-02-01', NULL),
 (57, 3, 1, NULL, 'All MHS101Referral records.', '2021-04-01', NULL),
 (57, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (57, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (57, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (57, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (57, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (58, 3, 1, NULL, 'All MHS201CareContact records.', '2021-04-01', NULL),
 (58, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (58, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (58, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (58, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (58, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (59, 3, 1, NULL, 'All MHS204IndirectActivity records.', '2021-04-01', NULL),
 (59,3,2,1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (59, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (59, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (59, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (59, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (60, 3, 1, NULL, 'All MHS301GroupSession records.', '2021-04-01', NULL),
 (60, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (60, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (60, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (60, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (60, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (61, 3, 1, NULL, 'All MHS512HospSpellCommAssPer records.', '2021-04-01', NULL),
 (61, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (61, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (61, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (61, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (61, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (62, 3, 1, NULL, 'All MHS517SMHExceptionalPackOfCare records.', '2021-04-01', NULL),
 (62, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (62, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (62, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (62, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (62, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),
 (63, 3, 1, NULL, 'All MHS608AnonSelfAssess records.', '2021-04-01', NULL),
 (63, 3, 2, 1, 'Records with an Organisation Identifier (code of Commissioner) that match a code of specialised responsible commissioner and that could be matched to an Organisation Identifier in the ODS Organisational tables  which was still open at the end of the reporting period.','2021-04-01', NULL),
 (63, 3, 2, 2, 'Records with an Organisation Identifier (code of Commissioner) that do not match a code of specialised responsible commissioner but that could be matched to an Organisation Identifier in the ODS Organisational tables   which was still open at the end of the reporting period.','2021-04-01', NULL),
 (63, 3, 2, 3, 'Records with an Organisation Identifier (code of Commissioner) equal to VPP00 or XMD00 or YDD82','2021-04-01', NULL),
 (63, 3, 2, 4, 'Records with an Organisation Identifier (code of Commissioner) that could not be matched to an Org Identifier in the ODS Organisational tables or which was matched to an Org Identifier which was closed prior to the day before the start of the reporting period.','2021-04-01', NULL),
 (63, 3, 2, 5, 'Records with no Organisation Identifier (code of Commissioner).','2021-04-01', NULL),

 -- new measures from CDQA team - start
 (64,3,1,NULL,'All MHS003AccommStatus Records','2022-03-17',NULL),
 (64,3,2,1,'Records where the Accommodation Type is valid in referance data','2022-03-17',NULL),
 (64,3,2,2,'Records with a Accommodation Type equals 98','2022-03-17',NULL),
 (64,3,2,4,'Records with a Accommodation Type not valid in referance data','2022-03-17',NULL),
 (64,3,2,5,'Records with No Accommodation Type','2022-03-17',NULL),

 (65,3,1,NULL,'All MHS004EmpStatus Records','2022-03-17',NULL),
 (65,3,2,1,'Records where the Employment Status equals 01, 02, 03, 04, 05, 06, 07, 08, ZZ','2022-03-17',NULL),
 (65,3,2,4,'Records with a Employment status not 01, 02, 03, 04, 05, 06, 07, 08, ZZ	','2022-03-17',NULL),
 (65,3,2,5,'Records with No Employment Status','2022-03-17',NULL),

 (66,3,1,NULL,'All MHS007DisabilityType Records','2022-03-17',NULL),
 (66,3,2,1,'Records where the Disibility Code equals 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, NN, ZZ','2022-03-17',NULL),
 (66,3,2,2,'Records where the Disibility Code equals XX','2022-03-17',NULL),
 (66,3,2,4,'Records with a Disibility Code not 01, 02, 03, 04, 05, 06, 07, 08, 09, 10, NN, ZZ, XX','2022-03-17',NULL),
 (66,3,2,5,'Records with No Disibility Code','2022-03-17',NULL),

 (67,3,1,NULL,'All MHS501HospProvSpell Records','2022-03-17',NULL),
 (67,3,2,1,'Records with a valid Decision to Admit Date date which is after the Reporting Period End Date','2022-03-17',NULL),
 (67,3,2,5,'Records with no Decision to Admit Date','2022-03-17',NULL),

 (68,3,1,NULL,'All MHS501HospProvSpell records','2022-03-17',NULL),
 (68,3,2,1,'Records with a valid Decision to Admit Time time','2022-03-17',NULL),
 (68,3,2,5,'Records with no valid Decision to Admit Time','2022-03-17',NULL),

 (69,3,1,NULL,'All MHS501HospProvSpell records','2022-03-17',NULL),
 (69,3,2,1,'Records where the Admission Source is valid in referance data','2022-03-17',NULL),
 (69,3,2,3,'Records where the Admission Source equals 98, 99','2022-03-17',NULL),
 (69,3,2,4,'Records with a Admission Source not valid in referance data','2022-03-17',NULL),
 (69,3,2,5,'Records with No Admission Source','2022-03-17',NULL),

 (70,3,1,NULL,'All MHS501HospProvSpell records','2022-03-17',NULL),
 (70,3,2,1,'Records where the Destination Of Discharge equals is valid in referance data','2022-03-17',NULL),
 (70,3,2,3,'Records where the Destination Of Discharge equals 98, 99','2022-03-17',NULL),
 (70,3,2,4,'Records with a Destination Of Discharge not valid in referance data','2022-03-17',NULL),
 (70,3,2,5,'Records with No Destination Of Discharge','2022-03-17',NULL),

 (71,3,1,NULL,'All MHS505RestrictiveInterventInc records','2022-03-17',NULL),
 (71,3,2,1,'Records with a valid Start Time (Restrictive Intervention Incident) time','2022-03-17',NULL),
 (71,3,2,5,'Records with no valid Start Time (Restrictive Intervention Incident)','2022-03-17',NULL),

 (72,3,1,NULL,'All MHS505RestrictiveInterventInc records','2022-03-17',NULL),
 (72,3,2,1,'Records where the Restrictive Intervention Reason equals 10, 11, 12, 13, 14, 15, 16, 17, 18, 19','2022-03-17',NULL),
 (72,3,2,2,'Records where the Restrictive Intervention Reason equals 98','2022-03-17',NULL),
 (72,3,2,3,'Records where the Restrictive Intervention Reason equals 99','2022-03-17',NULL),
 (72,3,2,4,'Records where the Restrictive Intervention Reason does not equal 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 98, 99','2022-03-17',NULL),
 (72,3,2,5,'Records with No Restrictive Intervention Reason','2022-03-17',NULL),

 (73,3,1,NULL,'All MHS515RestrictiveInterventType Records','2022-03-17',NULL),
 (73,3,2,1,'Records with a valid Start Time (Restrictive Intervention Type) time','2022-03-17',NULL),
 (73,3,2,5,'Records with no Start Time (Restrictive Intervention Type) time','2022-03-17',NULL),

 (74,3,1,NULL,'All MHS515RestrictiveInterventType Records','2022-03-17',NULL),
 (74,3,2,1,'Records where the Restrictive Intervention Type equals 01, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17','2022-03-17',NULL),
 (74,3,2,4,'Records where the Restrictive Intervention Type does not equal 01, 04, 05, 06, 07, 08, 09, 10, 11, 12, 13, 14, 15, 16, 17','2022-03-17',NULL),
 (74,3,2,5,'Records with No Restrictive Intervention Type','2022-03-17',NULL),

 (75,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (75,3,2,1,'Records where the Ward Setting Type (Mental Health) equals 01, 02, 03, 04, 05, 06','2022-03-17',NULL),
 (75,3,2,4,'Records where the Ward Setting Type (Mental Health) does not equal 01, 02, 03, 04, 05, 06','2022-03-17',NULL),
 (75,3,2,5,'Records with No Valid Ward Setting Type (Mental Health)','2022-03-17',NULL),

 (76,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (76,3,2,1,'Records where the Intended Age Group (Mental Health) equals 10, 11, 12, 13, 14, 15','2022-03-17',NULL),
 (76,3,2,2,'Records where the Intended Age Group (Mental Health) equals 99','2022-03-17',NULL),
 (76,3,2,4,'Records where the Intended Age Group (Mental Health) does not equal 10, 11, 12, 13, 14, 15, 99','2022-03-17',NULL),
 (76,3,2,5,'Records with No Valid Intended Age Group (Mental Health)','2022-03-17',NULL),

 (77,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (77,3,2,1,'Records where the Sex Of Patients Code (Mental Health) equals 1, 2','2022-03-17',NULL),
 (77,3,2,2,'Records where the Sex Of Patients Code (Mental Health) equals 8','2022-03-17',NULL),
 (77,3,2,4,'Records where the Sex Of Patients Code (Mental Health) does not equal 1, 2, 8','2022-03-17',NULL),
 (77,3,2,5,'Records with No Valid Sex Of Patients Code (Mental Health)','2022-03-17',NULL),

 (78,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (78,3,2,1,'Records where the Intended Clinical Care Intensity Code (Mental Health) equals 51, 52, 53, 61, 62, 63','2022-03-17',NULL),
 (78,3,2,4,'Records where the Intended Clinical Care Intensity Code (Mental Health) does not equal 51, 52, 53, 61, 62, 63','2022-03-17',NULL),
 (78,3,2,5,'Records with No Valid Intended Clinical Care Intensity Code (Mental Health)','2022-03-17',NULL),

 (79,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (79,3,2,1,'Records where the Ward Security Level equals 0, 1, 2, 3','2022-03-17',NULL),
 (79,3,2,4,'Records where the Ward Security Level does not equal 0, 1, 2, 3','2022-03-17',NULL),
 (79,3,2,5,'Records with No Valid Ward Security Level','2022-03-17',NULL),

 (80,3,1,NULL,'All MHS502WardStay Records','2022-03-17',NULL),
 (80,3,2,1,'Records where the Locked Ward Indicator equals Y, N','2022-03-17',NULL),
 (80,3,2,4,'Records where the Locked Ward Indicator does not equal Y, N','2022-03-17',NULL),
 (80,3,2,5,'Records with No Valid Locked Ward Indicator','2022-03-17',NULL),
 -- new measures from CDQA team - end

 -- Gender Measures 
 (81,3,1,NULL,'All MHS001MPI records.','2022-04-01',NULL),
 (81,3,2,1,'Records with a Gender Identity Code 1 - 3 or Z..','2022-04-01',NULL),
 (81,3,2,2,'Records with a Gender Identity Code 4.','2022-04-01',NULL),
 (81,3,2,3,'Records with a Gender Identity Code X','2022-04-01',NULL),
 (81,3,2,4,'Records with a Gender Identity Code not 1 - 4, Z, X and not missing.','2022-04-01',NULL),
 (81,3,2,5,'Records with no Gender Identity Code.','2022-04-01',NULL),

 (82,3,1,NULL,'All MHS001MPI records.','2022-04-01',NULL),
 (82,3,2,1,'Records with a Gender Identity Same At Birth Indicator Code Y, N or Z.','2022-04-01',NULL),
 -- (82,3,2,2,N/A,'2022-04-01',NULL),
 (82,3,2,3,'Records with a Gender Identity Same At Birth Indicator Code X.','2022-04-01',NULL),
 (82,3,2,4,'Records with a Gender Identity Same At Birth Indicator Code not Y, N, 9, X and not missing.','2022-04-01',NULL),
 (82,3,2,5,'Records with no Gender Identity Same At Birth Indicator Code.','2022-04-01',NULL),
 -- Gender Measures - end

 -- the rows below this point are INTEGRITY measures, the ones above are VALIDITY measures
 (1, 7, 1, NULL, 'Referrals where the Referral Request Received Date is in the reporting period and person is aged under 19', '2016-08-01', NULL),
 (1, 7, 2, 1, 'Referrals where the Referral Request Received Date is in the reporting period and person is aged under 19 and (CAMHSTier in (1,2,3,4, 9) or ServTeamTypeRefToMH in (''C05'',''C06'',''C07'',''C09'') or Treatment Function = 711 or ward type in (''01'',''02'')', '2016-08-01', NULL),
 (2, 7, 1, NULL, 'All Referrals where the Referral Request Received Date is in the reporting period and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (2, 7, 2, 1, 'Number of Referrals where the Referral Request Received Date is in the reporting period and Age at Service Referral Received Date is under 19 and Primary Reason for Referral = (''12'')', '2016-08-01', NULL),
 (3, 7, 1, NULL, 'All referrals where Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (3, 7, 2, 1, 'Records with a Procedure code of ''51484002'',''304891004'',''444175001'',''443730003'',''984421000000104'' and where procedure scheme in use is SNOMED, Primary Reason for Referral is Eating Disorder and Age at Service Referral Received Date is under 19', '2016-08-01', NULL),
 (4, 7, 1, NULL, 'All MHS201CareContact records with a care contact time and where the care contact time is not null', '2019-02-01', NULL),
 (4, 7, 2, 1, 'Records with a Care contact time that is XX:00', '2019-02-01', NULL),
 (5, 7, 1, NULL, 'All MHS201CareContact records with a care contact time and where the care contact time is not null', '2019-02-01', NULL),
 (5, 7, 2, 1, 'Records with a Care contact time that is 00:00', '2019-02-01', NULL),
 (6, 7, 1, NULL, 'All MHS105OnwardReferral records with a referral time and where the referral time is not null', '2019-02-01', NULL),
 (6, 7, 2, 1, 'Records with a referral time that is XX:00', '2019-02-01', NULL),
 (7, 7, 1, NULL, 'All MHS105OnwardReferral records with a referral time and where the referral time is not null', '2019-02-01', NULL),
 (7, 7, 2, 1, 'Records with a referral time that is 00:00', '2019-02-01', NULL),
 (8, 7, 1, NULL, 'All MHS204IndirectActivity records with an activity time and where the activity time is not null', '2019-02-01', NULL),
 (8, 7, 2, 1, 'Records with an activity time that is XX:00', '2019-02-01', NULL),
 (9, 7, 1, NULL, 'All MHS204IndirectActivity records with an activity time and where the activity time is not null', '2019-02-01', NULL),
 (9, 7, 2, 1, 'Records with an activity time that is 00:00', '2019-02-01', NULL),
 (10, 7, 1, NULL, 'All MHS101Referral records with a Discharge plan creation date with a plan creation time and where the plan creation time is not null', '2019-02-01', NULL),
 (10, 7, 2, 1, 'Records with a plan creation time that is XX:00', '2019-02-01', NULL),
 (11, 7, 1, NULL, 'All MHS101Referral records with a Discharge plan creation date with a plan creation time and where the plan creation time is not null', '2019-02-01', NULL),
 (11, 7, 2, 1, 'Records with a plan creation time that is 00:00', '2019-02-01', NULL),
 (12, 7, 1, NULL, 'All MHS101Referral records with a referral time and where the referral time is not null', '2019-02-01', NULL),
 (12, 7, 2, 1, 'Records with a referral time that is XX:00', '2019-02-01', NULL),
 (13, 7, 1, NULL, 'All MHS101Referral records with a referral time and where the referral time is not null', '2019-02-01', NULL),
 (13, 7, 2, 1, 'Records with a referral time that is 00:00', '2019-02-01', NULL),
 (14, 7, 1, NULL, 'All MHS101Referral records with a Discharge date with a service discharge time and where the service discharge time is not null', '2019-02-01', NULL),
 (14, 7, 2, 1, 'Records with a service discharge time that is XX:00', '2019-02-01', NULL),
 (15, 7, 1, NULL, 'All MHS101Referral records with a Discharge date with a service discharge time and where the service discharge time is not null', '2019-02-01', NULL),
 (15, 7, 2, 1, 'Records with a service discharge time that is 00:00', '2019-02-01', NULL),
 --mha new measures
 (16, 7, 1, NULL, 'All MHS401 records submitted in the reporting period', '2024-04-01', NULL),
 (16, 7, 2, 1, 'Records where ethnicity not recorded or is invalid', '2024-04-01', NULL),
 (17, 7, 1, NULL, 'All MHS401MHActPeriod records with a Mental Health Act Legal Status Classification Assignment Period start date and start time and where the start time is not null', '2024-04-01', NULL),
 (17, 7, 2, 1, 'Records with a Mental Health Act Legal Status Classification Assignment Period start time that is 00:00', '2024-04-01', NULL),
 (18, 7, 1, NULL, 'All MHS401MHActPeriod records with a Mental Health Act Legal Status Classification Assignment Period start date and start time and where the start time is not null', '2024-04-01', NULL),
 (18, 7, 2, 1, 'Records with a Mental Health Act Legal Status Classification Assignment Period start time that is 12:00', '2024-04-01', NULL),
 (19, 7, 1, NULL, 'All MHS401MHActPeriod records with a Mental Health Act Legal Status Classification Assignment Period start date and start time and where the start time is not null', '2024-04-01', NULL),
 (19, 7, 2, 1, 'Records with a Mental Health Act Legal Status Classification Assignment Period start time that is XX:00', '2024-04-01', NULL),
 (20, 7, 1, NULL, 'All MHS401MHActPeriod records from previous reporting period with a Mental Health Act Legal Status Classification Assignment Period end date as null', '2024-04-01', NULL),
 (20, 7, 2, 1, 'MHS401MHActPeriod records becoming inactive in the reporting period', '2024-04-01', NULL);

 ANALYZE TABLE $db.dq_measure_description COMPUTE STATISTICS FOR COLUMNS DimensionTypeId, MeasureId, MeasureTypeId, MetricTypeId;