-- Databricks notebook source
 %md

 #### SUPPRESS AND ROUND

-- COMMAND ----------

TRUNCATE TABLE $personal_db.Perinatal_output

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW ENGLAND AS 

SELECT 
REPORTING_PERIOD_START 
,REPORTING_PERIOD_END
,STATUS
,BREAKDOWN
,LEVEL as LEVEL_ONE
,LEVEL_DESCRIPTION as LEVEL_ONE_DESCRIPTION
,LEVEL_2 as LEVEL_TWO
,LEVEL_2_DESCRIPTION as LEVEL_TWO_DESCRIPTION
,METRIC
,cast(METRIC_VALUE as string) as METRIC_VALUE
FROM
$personal_db.Perinatal
WHERE
BREAKDOWN in ('England')

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW DEMOG_BREAKDOWNS AS 

SELECT 
REPORTING_PERIOD_START 
,REPORTING_PERIOD_END
,STATUS
,BREAKDOWN
,LEVEL as LEVEL_ONE
,LEVEL_DESCRIPTION as LEVEL_ONE_DESCRIPTION
,LEVEL_2 as LEVEL_TWO
,LEVEL_2_DESCRIPTION as LEVEL_TWO_DESCRIPTION
,METRIC
,cast(METRIC_VALUE as string) as METRIC_VALUE
FROM
$personal_db.Perinatal
WHERE
BREAKDOWN in ('Age at Booking','Ethnicity', 'IMD')

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW SubNational AS 

SELECT 
REPORTING_PERIOD_START
,REPORTING_PERIOD_END
,STATUS
,BREAKDOWN
,LEVEL
,LEVEL_DESCRIPTION
,LEVEL_2
,LEVEL_2_DESCRIPTION
,METRIC
,cast(case when cast(Metric_value as int) < 5 then '9999999' else cast(round(cast(metric_value as float)/5,0)*5 as int) end as string) as  METRIC_VALUE
FROM
$personal_db.Perinatal
WHERE
BREAKDOWN IN ('Provider','CCG', 'STP')

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW SubNational_Supp AS

SELECT 
REPORTING_PERIOD_START 
,REPORTING_PERIOD_END
,STATUS
,BREAKDOWN
,LEVEL as LEVEL_ONE
,LEVEL_DESCRIPTION as LEVEL_ONE_DESCRIPTION
,LEVEL_2 as LEVEL_TWO
,LEVEL_2_DESCRIPTION as LEVEL_TWO_DESCRIPTION
,METRIC
,case when METRIC_VALUE = '9999999' then '*' else METRIC_VALUE end  as metric_value
FROM 
SubNational

-- COMMAND ----------

 %md 

 #### Format output


-- COMMAND ----------

CREATE OR REPLACE  TEMPORARY VIEW RD_CCG_LATEST AS
SELECT 
DISTINCT 
'1' AS ID,
'CCG' AS BREAKDOWN,
ORG_CODE,
NAME

FROM $reference_data.org_daily

WHERE 
ORG_TYPE_CODE = 'CC'
AND BUSINESS_END_DATE IS NULL
AND NAME NOT LIKE '%HUB'
AND NAME NOT LIKE '%NATIONAL%'
AND (ORG_CLOSE_DATE >= add_months('$FY_START',-25) OR ISNULL(ORG_CLOSE_DATE))
UNION
SELECT
'1' AS ID,
'CCG' AS BREAKDOWN,
'UNKNOWN' AS ORG_CODE,
'UNKNOWN' AS NAME

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW RD_ORG_DAILY_LATEST AS
SELECT DISTINCT ORG_CODE, 
                NAME
           FROM $reference_data.org_daily
          WHERE (BUSINESS_END_DATE >= add_months('$RP_ENDDATE', 1) OR ISNULL(BUSINESS_END_DATE))
                AND BUSINESS_START_DATE <= add_months('$RP_ENDDATE', 1)	
                AND ORG_TYPE_CODE NOT IN ('MP', 'IR', 'F', 'GO', 'CN');

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW Provider_list AS
SELECT 
DISTINCT 
'1' AS ID,
'Provider' AS BREAKDOWN,
OrgIDProvider as ORG_CODE, 
x.NAME as NAME

FROM $MHSDS.MHS000Header as Z

LEFT OUTER JOIN RD_ORG_DAILY_LATEST AS X
              ON Z.OrgIDProvider = X.ORG_CODE

WHERE	Z.UniqMonthID between '$MONTH_ID' - 11 AND '$MONTH_ID' 


-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW STP_LIST AS

SELECT DISTINCT
'STP' AS BREAKDOWN,
STP_CODE,
STP_DESCRIPTION
FROM
global_temp.STP_MAPPING

UNION

SELECT 
'STP' AS BREAKDOWN,
'UNKNOWN' AS STP_CODE,
'UNKNOWN' AS STP_DESCRIPTION

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW Measures AS
SELECT 
DISTINCT 
BREAKDOWN, 
METRIC
FROM 
$personal_db.Perinatal

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW DEMOGRAPHICS AS 
SELECT 
DISTINCT 
BREAKDOWN,
LEVEL,
LEVEL_DESCRIPTION
FROM 
$personal_db.PERINATAL
WHERE
BREAKDOWN IN ('Age at Booking', 'Ethnicity', 'IMD')

-- COMMAND ----------

CREATE OR REPLACE TEMPORARY VIEW SubNatList AS

SELECT 
DISTINCT
A.BREAKDOWN,
B.ORG_CODE AS LEVEL,
B.NAME AS LEVEL_DESCRIPTION,
A.METRIC
FROM MEASURES A
CROSS JOIN PROVIDER_LIST B ON A.BREAKDOWN = B.BREAKDOWN

UNION ALL 

SELECT 
DISTINCT
A.BREAKDOWN,
B.ORG_CODE AS LEVEL,
B.NAME AS LEVEL_DESCRIPTION,
A.METRIC
FROM MEASURES A
CROSS JOIN RD_CCG_LATEST B ON A.BREAKDOWN = B.BREAKDOWN 

-- UNION ALL GVF removed this section in investigating Unknown Duplicates 7/2/2023

-- SELECT 
-- DISTINCT 
-- A.BREAKDOWN,
-- 'UNKNOWN' AS LEVEL,
-- 'UNKNOWN' AS LEVEL_DESCRIPTION,
-- A.METRIC
-- FROM MEASURES A
-- WHERE
-- A.BREAKDOWN = 'CCG'

UNION ALL

SELECT 
DISTINCT
A.BREAKDOWN,
B.STP_CODE AS LEVEL,
B.STP_DESCRIPTION AS LEVEL_DESCRIPTION,
A.METRIC
FROM MEASURES A
CROSS JOIN STP_LIST B ON A.BREAKDOWN = B.BREAKDOWN

UNION ALL

SELECT 
DISTINCT
A.BREAKDOWN,
B.LEVEL AS LEVEL,
B.LEVEL_DESCRIPTION AS LEVEL_DESCRIPTION,
A.METRIC
FROM MEASURES A
CROSS JOIN DEMOGRAPHICS B ON A.BREAKDOWN = B.BREAKDOWN

-- COMMAND ----------

INSERT INTO $personal_db.Perinatal_Output

SELECT 
 '$RP_STARTDATE' AS REPORTING_PERIOD_START 
,'$RP_ENDDATE' AS REPORTING_PERIOD_END
,'Final' AS STATUS
,BREAKDOWN
,LEVEL_ONE AS LEVEL_ONE
,LEVEL_ONE_DESCRIPTION AS LEVEL_ONE_DESCRIPTION
,'NONE' AS LEVEL_TWO
,'NONE' AS LEVEL_TWO_DESCRIPTION
,METRIC
,COALESCE(METRIC_VALUE,0) AS METRIC_VALUE
FROM 
England

-- COMMAND ----------

INSERT INTO $personal_db.Perinatal_Output

SELECT 
'$RP_STARTDATE' AS REPORTING_PERIOD_START 
,'$RP_ENDDATE' AS REPORTING_PERIOD_END
,'Final' AS STATUS
,A.BREAKDOWN
,A.LEVEL AS LEVEL_ONE
,A.LEVEL_DESCRIPTION AS LEVEL_ONE_DESCRIPTION
,'NONE' AS LEVEL_TWO
,'NONE' AS LEVEL_TWO_DESCRIPTION
,A.METRIC
,COALESCE(CAST(B.METRIC_VALUE as string),"*") AS METRIC_VALUE
FROM 
SubNatList A
LEFT JOIN SubNational_Supp B ON A.BREAKDOWN = B.BREAKDOWN AND A.LEVEL = B.LEVEL_ONE AND A.METRIC = B.METRIC
WHERE 
A.BREAKDOWN IN ('Provider','CCG','STP')

-- COMMAND ----------

INSERT INTO $personal_db.Perinatal_Output

SELECT 
 '$RP_STARTDATE' AS REPORTING_PERIOD_START 
,'$RP_ENDDATE' AS REPORTING_PERIOD_END
,'Final' AS STATUS
,A.BREAKDOWN
,A.LEVEL AS LEVEL_ONE
,A.LEVEL_DESCRIPTION AS LEVEL_ONE_DESCRIPTION
,'NONE' AS LEVEL_TWO
,'NONE' AS LEVEL_TWO_DESCRIPTION
,A.METRIC
,COALESCE(B.METRIC_VALUE,0) AS METRIC_VALUE
FROM 
SUBNATLIST A
LEFT JOIN DEMOG_BREAKDOWNS B ON A.BREAKDOWN = B.BREAKDOWN AND A.LEVEL = B.LEVEL_ONE AND A.METRIC = B.METRIC
WHERE 
A.BREAKDOWN IN ('Age at Booking', 'Ethnicity','IMD')